name: CI

on: [push, pull_request]

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven Checks
        run: |
          mvn clean install
